In [48]:
import pandas as pd
import numpy as np

# need to know categorical variables
from configs import PreprocessingConfig

# missforest
from msap.modeling.model_selection.preprocessing import Preprocessor
from missingpy import MissForest

# list of variables
vars_cat_prefs = PreprocessingConfig.columns_categorical
# not encoded
unencoded = pd.read_csv("./output/data_cleaned.csv")
# encoded
encoded = pd.read_csv("./output/data_cleaned_encoded_18_yesmental.csv")


In [49]:
encoded.dtypes

a520r_8wg            float64
a521r_8wg            float64
d781_12wg            float64
d801_12wg            float64
d602ar_12wg          float64
                      ...   
c801_32wg_9.0        float64
f501_8m_1.0          float64
f501_8m_2.0          float64
f501_8m_3.0          float64
y18CH_Dep_YN_216m    float64
Length: 119, dtype: object

In [50]:
for col in encoded.columns:
    if any([col.startswith(x) for x in vars_cat_prefs]):
        encoded[col] = encoded[col].astype("category")



In [51]:
encoded.dtypes

a520r_8wg             float64
a521r_8wg             float64
d781_12wg             float64
d801_12wg             float64
d602ar_12wg           float64
                       ...   
c801_32wg_9.0        category
f501_8m_1.0          category
f501_8m_2.0          category
f501_8m_3.0          category
y18CH_Dep_YN_216m     float64
Length: 119, dtype: object

In [52]:
def get_all_categorical(
        categorical: list,
        X: pd.DataFrame):

    names = []
    for feature in X.columns:
        if feature.startswith(tuple(categorical)):
            names.append(feature)
    # print(names)
    indices = [X.columns.get_loc(c) for c in names if c in X]
    return indices

In [53]:
cat_vars = get_all_categorical(vars_cat_prefs, encoded)

In [54]:
imputer = MissForest(n_jobs=1, verbose=0, random_state=42)
encoded = encoded.head(10)
print(encoded)
encoded.drop('y18CH_Dep_YN_216m', axis=1)
print(encoded)
data_new_df = pd.DataFrame(
            imputer.fit_transform(X=encoded, cat_vars=cat_vars),
            index=encoded.index,
            columns=encoded.columns)

   a520r_8wg  a521r_8wg  d781_12wg  d801_12wg  d602ar_12wg  b320_18wg  \
0        0.0        1.0       22.0       20.0          0.0        2.0   
1        1.0        1.0       26.0       24.0          0.0        3.0   
2        1.0        1.0       29.0       15.0          0.0        1.0   
3        0.0        1.0       27.0       17.0          1.0        2.0   
4        1.0        1.0       22.0       21.0          0.0        2.0   
5        0.0        1.0       25.0       25.0          0.0        1.0   
6        1.0        1.0       21.0       14.0          0.0        2.0   
7        1.0        1.0       26.0       23.0          0.0        2.0   
8        1.0        1.0       29.0       28.0          0.0        1.0   
9        1.0        1.0       23.0       23.0          0.0        1.0   

   b321_18wg  c601_32wg  c645_32wg  Max_ed_32wg  ...  c801_32wg_4.0  \
0        3.0        8.0        3.0          5.0  ...            0.0   
1        1.0        2.0        4.0          4.0  ...  

/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. U

[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 0. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 1. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


Iteration: 0


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. U

[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 0. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 1. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


Iteration: 1


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. U

[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 0. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Iteration: 2


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. U

[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 0. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 21. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 0. 1. 1. 1. 1. 1. 1. 1.]
[[ 0.  1. 22. ...  0.  0.  0.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 1.  1. 29. ...  0.  0.  0.]
 ...
 [ 1.  1. 26. ...  0.  0.  1.]
 [ 1.  1. 29. ...  0.  0.  0.]
 [ 1.  1. 23. ...  0.  0.  0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Iteration: 3


/Users/arielleyoo/opt/anaconda3/envs/.depressionnew/lib/python3.10/site-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


In [46]:
data_new_df

a520r_8wg  a521r_8wg  d781_12wg  d801_12wg  d602ar_12wg  b320_18wg  \
0        0.0        1.0       22.0       20.0          0.0        2.0   
1        1.0        1.0       26.0       24.0          0.0        3.0   
2        1.0        1.0       29.0       15.0          0.0        1.0   
3        0.0        1.0       27.0       17.0          1.0        2.0   
4        1.0        1.0       22.0       21.0          0.0        2.0   
5        0.0        1.0       25.0       25.0          0.0        1.0   
6        1.0        1.0       21.0       14.0          0.0        2.0   
7        1.0        1.0       26.0       23.0          0.0        2.0   
8        1.0        1.0       29.0       28.0          0.0        1.0   
9        1.0        1.0       23.0       23.0          0.0        1.0   

   b321_18wg  c601_32wg  c645_32wg  Max_ed_32wg  ...  c801_32wg_4.0  \
0        3.0       8.00        3.0          5.0  ...            0.0   
1        1.0       2.00        4.0          4.0  ...            0.0   
2        2.0       7.00        5.0          5.0  ...            0.0   
3        2.0       8.75        3.0          3.0  ...            0.0   
4        2.0      13.00        3.0          4.0  ...            0.0   
5        1.0       5.00        1.0          1.0  ...            0.0   
6        2.0       8.00        3.0          3.0  ...            0.0   
7        2.0      13.00        1.0          4.0  ...            0.0   
8        1.0       3.00        2.0          2.0  ...            0.0   
9        1.0       2.00        5.0          5.0  ...            0.0   

   c801_32wg_5.0  c801_32wg_6.0  c801_32wg_7.0  c801_32wg_8.0  c801_32wg_9.0  \
0            0.0            0.0            0.0            0.0            0.0   
1            0.0            0.0            0.0            0.0            0.0   
2            0.0            0.0            0.0            0.0            0.0   
3            0.0            0.0            0.0            0.0            0.0   
4            0.0            0.0            0.0            0.0            0.0   
5            0.0            0.0            0.0            0.0            0.0   
6            0.0            0.0            0.0            0.0            0.0   
7            0.0            0.0            0.0            0.0            0.0   
8            0.0            0.0            0.0            0.0            0.0   
9            0.0            0.0            0.0            0.0            0.0   

   f501_8m_1.0  f501_8m_2.0  f501_8m_3.0  y18CH_Dep_YN_216m  
0          1.0          0.0          0.0                0.0  
1          1.0          0.0          0.0                0.0  
2          1.0          0.0          0.0                0.0  
3          1.0          0.0          0.0                1.0  
4          1.0          0.0          0.0                0.0  
5          1.0          0.0          0.0                1.0  
6          1.0          0.0          0.0                0.0  
7          1.0          0.0          0.0                1.0  
8          1.0          0.0          0.0                0.0  
9          1.0          0.0          0.0                0.0  

[10 rows x 119 columns]

In [47]:


# check datatype of not encoded data for categorical variables
# unencoded_cols = unencoded.columns
# wrong_dtype = []
# for var in vars_cat_prefs:
#     if unencoded[var].dtype

# check datatype of encoded data for categorical variables


# compare diff as well just for kicks
